version: 1.0.{build}
image: Visual Studio 2017
environment:
  NODEJS_VERSION: 8
  matrix:
  - TEMPLATE: angularjs
  - TEMPLATE: empty
  - TEMPLATE: inferno
  - TEMPLATE: react
  - TEMPLATE: vue
cache:
    - node_modules
    - '%LOCALAPPDATA%\Yarn'
install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    yarn

build_script:
- ps: >-
    npm run build
    
    npm link --silent

test_script:
- ps: >-
    instapack --version

    mkdir demo

    cd demo

    ipack new $env:TEMPLATE

    ipack

    ipack -xd
