version: 1.0.{build}
image: Visual Studio 2017
environment:
  NODEJS_VERSION: 8
cache:
    - '%APPDATA%\npm-cache'
install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    npm link

build_script:
- ps: >-
    npm run build

test_script:
- ps: >-
    mkdir demo

    cd demo

    Remove-Item * -Recurse; ipack new angularjs; ipack; ipack -dx

    Remove-Item * -Recurse; ipack new empty; ipack; ipack -dx

    Remove-Item * -Recurse; ipack new inferno; ipack; ipack -dx

    Remove-Item * -Recurse; ipack new react; ipack; ipack -dx

    Remove-Item * -Recurse; ipack new vue; ipack; ipack -dx

    Remove-Item * -Recurse; ipack new vue-mobile; ipack; ipack -dx
