version: 1.0.{build}
image: Visual Studio 2017
environment:
  NODEJS_VERSION: 8
  matrix:
  - TEMPLATE: angular-bootstrap
  - TEMPLATE: angular-material
  - TEMPLATE: empty
  - TEMPLATE: inferno
  - TEMPLATE: react
  - TEMPLATE: vue
  - TEMPLATE: vue+
test: off
install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    npm install -g npm@latest-4     # fixes build break due to npm 5 vs fsevents in Windows
    
    yarn

cache: '%LOCALAPPDATA%\Yarn'
build_script:
- ps: >-
    npm run build
    
    npm link

    instapack --version

    mkdir demo

    cd demo

    ipack new $env:TEMPLATE

    ipack

    ipack -od

    ipack -p

    ipack clean