version: 1.0.{build}
image: Visual Studio 2017
environment:
    matrix:
        - nodejs_version: "8"
        - nodejs_version: "10"
cache:
    - '%APPDATA%\npm-cache'
install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    npm link --loglevel error

build_script:
- ps: >-
    npm run build

test_script:
- ps: >-
    mkdir demo

    cd demo

    ipack set package-manager npm # prevents DeprecationWarning on AppVeyor Yarn 1.5.1

    function FullCycleTest { Remove-Item * -Recurse; ipack new $args[0]; ipack; ipack -dx }

    FullCycleTest vue

    FullCycleTest react

    FullCycleTest preact

    FullCycleTest inferno
